batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 245
lr: 0.0025912845602823636
nn_config:
  attn_dropout: 0.13954234853625858
  dropout: 0.6215065742479887
  hid_size: 57
  include_first_norm: false
  num_heads: 8
  num_layers: 4
  use_token: false
nn_name: fttransformer
patience: 30
time_budget: 36000
