batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 212
lr: 0.0001136699350140982
nn_config:
  attn_dropout: 0.537792410888989
  dropout: 0.16252449557069826
  hid_size: 170
  include_first_norm: false
  num_heads: 7
  num_layers: 5
  use_token: false
nn_name: fttransformer
patience: 30
time_budget: 36000
