batch_size: 2944
conv:
  num_heads: 2
dropout: 0.4208751652399052
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 20
feat_encode_size: 29
hid_size: 81
lr: 0.0012168333694312218
patience: 30
predictor: null
time_budget: 36000
