batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 142
lr: 0.002494529241277631
nn_config:
  attn_dropout: 0.03228098330146334
  dropout: 0.958517009922972
  hid_size: 224
  include_first_norm: false
  num_heads: 6
  num_layers: 8
  use_token: true
nn_name: fttransformer
patience: 30
time_budget: 36000
