batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 113
lr: 0.003840235275090584
nn_config:
  attn_dropout: 0.8347115536979375
  dropout: 0.8779523514131061
  hid_size: 78
  include_first_norm: false
  num_heads: 2
  num_layers: 4
  use_token: true
nn_name: fttransformer
patience: 30
time_budget: 36000
