batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 38
lr: 0.0002091603626092
nn_config:
  attn_dropout: 0.06224822516000961
  dropout: 0.10612856243044644
  hid_size: 140
  include_first_norm: false
  num_heads: 4
  num_layers: 7
  use_token: false
nn_name: fttransformer
patience: 30
time_budget: 36000
