batch_size: 2637
conv:
  num_heads: 3
dropout: 0.0340714485989152
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 20
- 20
- 20
feat_encode_size: 226
hid_size: 85
lr: 0.001148407181785362
patience: 30
predictor: null
time_budget: 36000
