batch_size: 1176
conv:
  num_heads: 3
dropout: 0.1155987792786739
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 20
- 20
- 20
feat_encode_size: 30
hid_size: 245
lr: 0.0005827419291910945
patience: 30
predictor: null
time_budget: 36000
