batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 13
lr: 0.005628866060264327
nn_config:
  attn_dropout: 0.14030950959644506
  dropout: 0.4176224885879693
  hid_size: 55
  include_first_norm: true
  num_heads: 5
  num_layers: 3
  use_token: false
nn_name: fttransformer
patience: 30
time_budget: 36000
