batch_size: 4011
epochs: 500
eval_batch_size: 4096
feat_encode_size: 92
lr: 0.0006141316101985213
nn_config:
  attn_dropout: 0.04753283394258212
  dropout: 0.3052909304177164
  hid_size: 85
  include_first_norm: false
  num_heads: 8
  num_layers: 3
  use_token: false
nn_name: fttransformer
patience: 30
time_budget: 36000
