batch_size: 3211
conv:
  num_heads: 3
dropout: 0.048040552638880185
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 5
- 5
- 5
feat_encode_size: 124
hid_size: 169
lr: 0.00025228034801344826
patience: 30
predictor: null
time_budget: 36000
