batch_size: 394
dropout: 0.18155644557394823
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 5
- 5
- 5
feat_encode_size: 180
hid_size: 105
lr: 0.0006186485554642047
patience: 30
predictor: null
time_budget: 36000
use_multiprocessing: true
