batch_size: 1300
conv:
  num_heads: 1
dropout: 0.24543982895798555
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 20
- 20
feat_encode_size: 80
hid_size: 219
lr: 0.0014809639796811477
patience: 30
predictor: null
time_budget: 36000
