batch_size: 2957
conv:
  num_heads: 5
dropout: 0.07272389772879795
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 5
- 5
- 5
feat_encode_size: 26
hid_size: 79
lr: 0.00026112645379689777
patience: 30
predictor: null
time_budget: 36000
