batch_size: 3301
conv:
  num_heads: 5
dropout: 0.4612162887474152
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 20
- 20
feat_encode_size: 60
hid_size: 77
lr: 0.0011635114017402456
patience: 30
predictor: null
time_budget: 36000
