batch_size: 2496
dropout: 0.10185598438114007
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 4096
eval_trials: 3
fanouts:
- 10
- 10
feat_encode_size: 68
hid_size: 183
lr: 0.0033014788743448327
patience: 30
predictor: null
time_budget: 36000
use_multiprocessing: true
