batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 230
lr: 0.009877074062906811
nn_config:
  attn_dropout: 0.16281425803283966
  dropout: 0.9075095613418132
  hid_size: 16
  include_first_norm: false
  num_heads: 7
  num_layers: 6
  use_token: true
nn_name: fttransformer
patience: 30
time_budget: 36000
