batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 180
lr: 0.0017753103528886066
nn_config:
  attn_dropout: 0.4386749960830571
  dropout: 0.7016431473906605
  hid_size: 49
  include_first_norm: true
  num_heads: 4
  num_layers: 2
  use_token: false
nn_name: fttransformer
patience: 30
time_budget: 36000
