batch_size: 1853
conv:
  num_heads: 5
dropout: 0.0984259947481797
enable_temporal_sampling: true
epochs: 500
eval_batch_size: 1024
eval_trials: 3
fanouts:
- 10
- 10
- 10
- 10
feat_encode_size: 154
hid_size: 247
lr: 0.0005653411997999571
patience: 30
predictor: null
time_budget: 36000
