batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 42
lr: 0.0019309915717807572
nn_config:
  attn_dropout: 0.9642558101432922
  dropout: 0.5082014594676663
  hid_size: 192
  include_first_norm: false
  num_heads: 6
  num_layers: 6
  use_token: false
nn_name: fttransformer
patience: 30
time_budget: 36000
