batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 44
lr: 0.005536724808921111
nn_config:
  attn_dropout: 0.800068137444257
  dropout: 0.8313626396067535
  hid_size: 110
  include_first_norm: false
  num_heads: 3
  num_layers: 3
  use_token: true
nn_name: fttransformer
patience: 30
time_budget: 36000
