batch_size: 4096
epochs: 500
eval_batch_size: 4096
feat_encode_size: 23
lr: 0.0069986670413804885
nn_config:
  attn_dropout: 0.5842702826174441
  dropout: 0.41433885935015713
  hid_size: 87
  include_first_norm: false
  num_heads: 7
  num_layers: 6
  use_token: true
nn_name: fttransformer
patience: 30
time_budget: 36000
